"""add budget_summary table

Revision ID: e243279f952f
Revises: 9daa015274dd
Create Date: 2026-02-20 01:50:46.010955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'e243279f952f'
down_revision: Union[str, Sequence[str], None] = '9daa015274dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget_summary',
    sa.Column('baseline_simulation_id', sa.Uuid(), nullable=False),
    sa.Column('reform_simulation_id', sa.Uuid(), nullable=False),
    sa.Column('report_id', sa.Uuid(), nullable=True),
    sa.Column('variable_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('baseline_total', sa.Float(), nullable=True),
    sa.Column('reform_total', sa.Float(), nullable=True),
    sa.Column('change', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['baseline_simulation_id'], ['simulations.id'], ),
    sa.ForeignKeyConstraint(['reform_simulation_id'], ['simulations.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('budget_summary')
    # ### end Alembic commands ###
