"""add_congressional_district_impacts_table

Revision ID: a5e4144467e5
Revises: 75e5dca14603
Create Date: 2026-02-20 20:52:53.243197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5e4144467e5'
down_revision: Union[str, Sequence[str], None] = '75e5dca14603'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('congressional_district_impacts',
    sa.Column('baseline_simulation_id', sa.Uuid(), nullable=False),
    sa.Column('reform_simulation_id', sa.Uuid(), nullable=False),
    sa.Column('report_id', sa.Uuid(), nullable=True),
    sa.Column('district_geoid', sa.Integer(), nullable=False),
    sa.Column('state_fips', sa.Integer(), nullable=False),
    sa.Column('district_number', sa.Integer(), nullable=False),
    sa.Column('average_household_income_change', sa.Float(), nullable=False),
    sa.Column('relative_household_income_change', sa.Float(), nullable=False),
    sa.Column('population', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['baseline_simulation_id'], ['simulations.id'], ),
    sa.ForeignKeyConstraint(['reform_simulation_id'], ['simulations.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('congressional_district_impacts')
    # ### end Alembic commands ###
