"""add intra_decile_impacts table

Revision ID: 75e5dca14603
Revises: e243279f952f
Create Date: 2026-02-20 16:39:57.387711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75e5dca14603'
down_revision: Union[str, Sequence[str], None] = 'e243279f952f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intra_decile_impacts',
    sa.Column('baseline_simulation_id', sa.Uuid(), nullable=False),
    sa.Column('reform_simulation_id', sa.Uuid(), nullable=False),
    sa.Column('report_id', sa.Uuid(), nullable=True),
    sa.Column('decile', sa.Integer(), nullable=False),
    sa.Column('lose_more_than_5pct', sa.Float(), nullable=True),
    sa.Column('lose_less_than_5pct', sa.Float(), nullable=True),
    sa.Column('no_change', sa.Float(), nullable=True),
    sa.Column('gain_less_than_5pct', sa.Float(), nullable=True),
    sa.Column('gain_more_than_5pct', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['baseline_simulation_id'], ['simulations.id'], ),
    sa.ForeignKeyConstraint(['reform_simulation_id'], ['simulations.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('intra_decile_impacts')
    # ### end Alembic commands ###
