"""add user_simulation_associations table

Revision ID: 621977f3b1aa
Revises: drop_parent_report
Create Date: 2026-02-19 00:37:43.378088

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "621977f3b1aa"
down_revision: Union[str, Sequence[str], None] = "drop_parent_report"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_simulation_associations",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("simulation_id", sa.Uuid(), nullable=False),
        sa.Column("country_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("label", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["simulation_id"],
            ["simulations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_simulation_associations_simulation_id"),
        "user_simulation_associations",
        ["simulation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_simulation_associations_user_id"),
        "user_simulation_associations",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_user_simulation_associations_user_id"),
        table_name="user_simulation_associations",
    )
    op.drop_index(
        op.f("ix_user_simulation_associations_simulation_id"),
        table_name="user_simulation_associations",
    )
    op.drop_table("user_simulation_associations")
    # ### end Alembic commands ###
