"""add_decile_type_to_intra_decile_impacts

Revision ID: 8d54837f0fcd
Revises: a4ee5758d272
Create Date: 2026-02-20 22:50:00.125733

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8d54837f0fcd"
down_revision: Union[str, Sequence[str], None] = "a4ee5758d272"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "intra_decile_impacts",
        sa.Column(
            "decile_type",
            sqlmodel.sql.sqltypes.AutoString(),
            server_default="income",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("intra_decile_impacts", "decile_type")
    # ### end Alembic commands ###
