"""add user_report_associations table

Revision ID: 9daa015274dd
Revises: 621977f3b1aa
Create Date: 2026-02-19 16:58:03.157551

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9daa015274dd"
down_revision: Union[str, Sequence[str], None] = "621977f3b1aa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_report_associations",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("report_id", sa.Uuid(), nullable=False),
        sa.Column("country_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("label", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("last_run_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["reports.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_report_associations_report_id"),
        "user_report_associations",
        ["report_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_report_associations_user_id"),
        "user_report_associations",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_user_report_associations_user_id"),
        table_name="user_report_associations",
    )
    op.drop_index(
        op.f("ix_user_report_associations_report_id"),
        table_name="user_report_associations",
    )
    op.drop_table("user_report_associations")
    # ### end Alembic commands ###
