"""add_constituency_impacts_table

Revision ID: 83ceeb90bd74
Revises: a5e4144467e5
Create Date: 2026-02-20 21:44:14.780195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '83ceeb90bd74'
down_revision: Union[str, Sequence[str], None] = 'a5e4144467e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('constituency_impacts',
    sa.Column('baseline_simulation_id', sa.Uuid(), nullable=False),
    sa.Column('reform_simulation_id', sa.Uuid(), nullable=False),
    sa.Column('report_id', sa.Uuid(), nullable=True),
    sa.Column('constituency_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('constituency_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('x', sa.Integer(), nullable=False),
    sa.Column('y', sa.Integer(), nullable=False),
    sa.Column('average_household_income_change', sa.Float(), nullable=False),
    sa.Column('relative_household_income_change', sa.Float(), nullable=False),
    sa.Column('population', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['baseline_simulation_id'], ['simulations.id'], ),
    sa.ForeignKeyConstraint(['reform_simulation_id'], ['simulations.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('constituency_impacts')
    # ### end Alembic commands ###
