"""initial schema

Revision ID: 36f9d434e95b
Revises:
Create Date: 2026-02-07 01:52:16.497121

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "36f9d434e95b"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dynamics",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "policies",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tax_benefit_models",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("first_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("last_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "datasets",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("filepath", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("is_output_dataset", sa.Boolean(), nullable=False),
        sa.Column("tax_benefit_model_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tax_benefit_model_id"],
            ["tax_benefit_models.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "household_jobs",
        sa.Column(
            "tax_benefit_model_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("request_data", sa.JSON(), nullable=True),
        sa.Column("policy_id", sa.Uuid(), nullable=True),
        sa.Column("dynamic_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING", "RUNNING", "COMPLETED", "FAILED", name="householdjobstatus"
            ),
            nullable=False,
        ),
        sa.Column("error_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["dynamic_id"],
            ["dynamics.id"],
        ),
        sa.ForeignKeyConstraint(
            ["policy_id"],
            ["policies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tax_benefit_model_versions",
        sa.Column("model_id", sa.Uuid(), nullable=False),
        sa.Column("version", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["tax_benefit_models.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "dataset_versions",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("dataset_id", sa.Uuid(), nullable=False),
        sa.Column("tax_benefit_model_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["datasets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tax_benefit_model_id"],
            ["tax_benefit_models.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "parameters",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("label", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("data_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("unit", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("tax_benefit_model_version_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tax_benefit_model_version_id"],
            ["tax_benefit_model_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "simulations",
        sa.Column("dataset_id", sa.Uuid(), nullable=False),
        sa.Column("policy_id", sa.Uuid(), nullable=True),
        sa.Column("dynamic_id", sa.Uuid(), nullable=True),
        sa.Column("tax_benefit_model_version_id", sa.Uuid(), nullable=False),
        sa.Column("output_dataset_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING", "RUNNING", "COMPLETED", "FAILED", name="simulationstatus"
            ),
            nullable=False,
        ),
        sa.Column("error_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["datasets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["dynamic_id"],
            ["dynamics.id"],
        ),
        sa.ForeignKeyConstraint(
            ["output_dataset_id"],
            ["datasets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["policy_id"],
            ["policies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tax_benefit_model_version_id"],
            ["tax_benefit_model_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "variables",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("entity", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("data_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("possible_values", sa.JSON(), nullable=True),
        sa.Column("tax_benefit_model_version_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tax_benefit_model_version_id"],
            ["tax_benefit_model_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "parameter_values",
        sa.Column("parameter_id", sa.Uuid(), nullable=False),
        sa.Column("value_json", sa.JSON(), nullable=True),
        sa.Column("start_date", sa.DateTime(), nullable=False),
        sa.Column("end_date", sa.DateTime(), nullable=True),
        sa.Column("policy_id", sa.Uuid(), nullable=True),
        sa.Column("dynamic_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dynamic_id"],
            ["dynamics.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parameter_id"],
            ["parameters.id"],
        ),
        sa.ForeignKeyConstraint(
            ["policy_id"],
            ["policies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "reports",
        sa.Column("label", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("markdown", sa.Text(), nullable=True),
        sa.Column("parent_report_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("PENDING", "RUNNING", "COMPLETED", "FAILED", name="reportstatus"),
            nullable=False,
        ),
        sa.Column("error_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("baseline_simulation_id", sa.Uuid(), nullable=True),
        sa.Column("reform_simulation_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["baseline_simulation_id"],
            ["simulations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_report_id"],
            ["reports.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reform_simulation_id"],
            ["simulations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "aggregates",
        sa.Column("simulation_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("report_id", sa.Uuid(), nullable=True),
        sa.Column("variable", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "aggregate_type",
            sa.Enum("SUM", "MEAN", "COUNT", name="aggregatetype"),
            nullable=False,
        ),
        sa.Column("entity", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("filter_config", sa.JSON(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING", "RUNNING", "COMPLETED", "FAILED", name="aggregatestatus"
            ),
            nullable=False,
        ),
        sa.Column("error_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("result", sa.Float(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["reports.id"],
        ),
        sa.ForeignKeyConstraint(
            ["simulation_id"],
            ["simulations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "change_aggregates",
        sa.Column("baseline_simulation_id", sa.Uuid(), nullable=False),
        sa.Column("reform_simulation_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("report_id", sa.Uuid(), nullable=True),
        sa.Column("variable", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "aggregate_type",
            sa.Enum("SUM", "MEAN", "COUNT", name="changeaggregatetype"),
            nullable=False,
        ),
        sa.Column("entity", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("filter_config", sa.JSON(), nullable=True),
        sa.Column("change_geq", sa.Float(), nullable=True),
        sa.Column("change_leq", sa.Float(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "RUNNING",
                "COMPLETED",
                "FAILED",
                name="changeaggregatestatus",
            ),
            nullable=False,
        ),
        sa.Column("error_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("result", sa.Float(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["baseline_simulation_id"],
            ["simulations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reform_simulation_id"],
            ["simulations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["reports.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "decile_impacts",
        sa.Column("baseline_simulation_id", sa.Uuid(), nullable=False),
        sa.Column("reform_simulation_id", sa.Uuid(), nullable=False),
        sa.Column("report_id", sa.Uuid(), nullable=True),
        sa.Column(
            "income_variable", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("entity", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("decile", sa.Integer(), nullable=False),
        sa.Column("quantiles", sa.Integer(), nullable=False),
        sa.Column("baseline_mean", sa.Float(), nullable=True),
        sa.Column("reform_mean", sa.Float(), nullable=True),
        sa.Column("absolute_change", sa.Float(), nullable=True),
        sa.Column("relative_change", sa.Float(), nullable=True),
        sa.Column("count_better_off", sa.Float(), nullable=True),
        sa.Column("count_worse_off", sa.Float(), nullable=True),
        sa.Column("count_no_change", sa.Float(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["baseline_simulation_id"],
            ["simulations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reform_simulation_id"],
            ["simulations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["reports.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "inequality",
        sa.Column("simulation_id", sa.Uuid(), nullable=False),
        sa.Column("report_id", sa.Uuid(), nullable=True),
        sa.Column(
            "income_variable", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("entity", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("gini", sa.Float(), nullable=True),
        sa.Column("top_10_share", sa.Float(), nullable=True),
        sa.Column("top_1_share", sa.Float(), nullable=True),
        sa.Column("bottom_50_share", sa.Float(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["reports.id"],
        ),
        sa.ForeignKeyConstraint(
            ["simulation_id"],
            ["simulations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "poverty",
        sa.Column("simulation_id", sa.Uuid(), nullable=False),
        sa.Column("report_id", sa.Uuid(), nullable=True),
        sa.Column("poverty_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("entity", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("filter_variable", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("headcount", sa.Float(), nullable=True),
        sa.Column("total_population", sa.Float(), nullable=True),
        sa.Column("rate", sa.Float(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["reports.id"],
        ),
        sa.ForeignKeyConstraint(
            ["simulation_id"],
            ["simulations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "program_statistics",
        sa.Column("baseline_simulation_id", sa.Uuid(), nullable=False),
        sa.Column("reform_simulation_id", sa.Uuid(), nullable=False),
        sa.Column("report_id", sa.Uuid(), nullable=True),
        sa.Column("program_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("entity", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_tax", sa.Boolean(), nullable=False),
        sa.Column("baseline_total", sa.Float(), nullable=True),
        sa.Column("reform_total", sa.Float(), nullable=True),
        sa.Column("change", sa.Float(), nullable=True),
        sa.Column("baseline_count", sa.Float(), nullable=True),
        sa.Column("reform_count", sa.Float(), nullable=True),
        sa.Column("winners", sa.Float(), nullable=True),
        sa.Column("losers", sa.Float(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["baseline_simulation_id"],
            ["simulations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reform_simulation_id"],
            ["simulations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["reports.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("program_statistics")
    op.drop_table("poverty")
    op.drop_table("inequality")
    op.drop_table("decile_impacts")
    op.drop_table("change_aggregates")
    op.drop_table("aggregates")
    op.drop_table("reports")
    op.drop_table("parameter_values")
    op.drop_table("variables")
    op.drop_table("simulations")
    op.drop_table("parameters")
    op.drop_table("dataset_versions")
    op.drop_table("tax_benefit_model_versions")
    op.drop_table("household_jobs")
    op.drop_table("datasets")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("tax_benefit_models")
    op.drop_table("policies")
    op.drop_table("dynamics")
    # ### end Alembic commands ###
