"""add household support

Revision ID: f419b5f4acba
Revises: 36f9d434e95b
Create Date: 2026-02-07 01:56:31.064511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f419b5f4acba'
down_revision: Union[str, Sequence[str], None] = '36f9d434e95b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('households',
    sa.Column('tax_benefit_model_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('household_data', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_household_associations',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('household_id', sa.Uuid(), nullable=False),
    sa.Column('country_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_household_associations_household_id'), 'user_household_associations', ['household_id'], unique=False)
    op.create_index(op.f('ix_user_household_associations_user_id'), 'user_household_associations', ['user_id'], unique=False)
    op.add_column('reports', sa.Column('report_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # Create enum type first
    simulationtype = postgresql.ENUM('HOUSEHOLD', 'ECONOMY', name='simulationtype', create_type=False)
    simulationtype.create(op.get_bind(), checkfirst=True)
    op.add_column('simulations', sa.Column('simulation_type', sa.Enum('HOUSEHOLD', 'ECONOMY', name='simulationtype', create_type=False), nullable=False))
    op.add_column('simulations', sa.Column('household_id', sa.Uuid(), nullable=True))
    op.add_column('simulations', sa.Column('household_result', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.alter_column('simulations', 'dataset_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(None, 'simulations', 'households', ['household_id'], ['id'])
    op.add_column('variables', sa.Column('default_value', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('variables', 'default_value')
    op.drop_constraint(None, 'simulations', type_='foreignkey')
    op.alter_column('simulations', 'dataset_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('simulations', 'household_result')
    op.drop_column('simulations', 'household_id')
    op.drop_column('simulations', 'simulation_type')
    # Drop enum type
    postgresql.ENUM('HOUSEHOLD', 'ECONOMY', name='simulationtype').drop(op.get_bind(), checkfirst=True)
    op.drop_column('reports', 'report_type')
    op.drop_index(op.f('ix_user_household_associations_user_id'), table_name='user_household_associations')
    op.drop_index(op.f('ix_user_household_associations_household_id'), table_name='user_household_associations')
    op.drop_table('user_household_associations')
    op.drop_table('households')
    # ### end Alembic commands ###
